### ISSUE TITLE
Parse + React + Jest = Headers User-Agent forbidden

### ISSUE THREAD

**Issue by vince1995** [parse-community/Parse-SDK-JS#1051]
### Issue Description

I have a react app and want to test it with jest. In my app I am creating some requests to my parse server via the Parse SDK. It's because parse is setting the user agent [here](https://github.com/parse-community/Parse-SDK-JS/blob/e974daf6086d1d02a6cf36f873f820a9a11d489f/src/RESTController.js#L153) and jsdom [throws an error ](https://github.com/jsdom/jsdom/blob/master/lib/jsdom/living/xhr/xhr-utils.js#L81).

### Steps to reproduce

Create a react app, make a request to a parse server in it, run tests with jest (jsdom).

### Logs/Trace

```
      Error: Headers User-Agent forbidden
          at dispatchError (/mnt/c/Users/admin/Desktop/GitHub/calimoto-web/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:65:19)
          at validCORSPreflightHeaders (/mnt/c/Users/admin/Desktop/GitHub/calimoto-web/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:102:5)
          at Request.<anonymous> (/mnt/c/Users/admin/Desktop/GitHub/calimoto-web/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:380:12)
          at Request.emit (events.js:210:5)
          at Request.onRequestResponse (/mnt/c/Users/admin/Desktop/GitHub/calimoto-web/node_modules/request/request.js:1066:10)
          at ClientRequest.emit (events.js:210:5)
          at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:583:27)
          at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)
          at Socket.socketOnData (_http_client.js:456:22)
          at Socket.emit (events.js:210:5) undefined
```

### Solution:
The `IS_NODE` var should be false if `window` is not undefined.

**Comment by dplewis** [comment]
@vince1995 Can you try setting `access-control-allow-headers` or enable cors on your server?

**Comment by dplewis** [comment]
As a workaround you could do `Parse.CoreManager.set('IS_NODE', false)`;

It should false for you as you are in a browser with react.

**Comment by vince1995** [comment]
Thanks for the response. The workaround works. But I will also try to set the headers.

**Comment by dplewis** [comment]
Please feel free to open a PR to fix the IS_NODE variable for your React system.
