### ISSUE TITLE
Implementing password reset with Mailgun

### ISSUE THREAD

**Issue by REPTILEHAUS** [parse-community/Parse-SDK-JS#1082]
**Is your feature request related to a problem? Please describe.**
Im trying to implement password reset functionality (`"parse": "^2.10.0",`) 

In my app I am using the following endpoint ` return <IUser>(<ParseUser>await Parse.User.requestPasswordReset(email));`

On the parse server side I am using the following which I assume is correct

```parseConfig.emailAdapter = {
        module: 'parse-server-mailgun',
        options: {
            fromAddress: "hello@site.com",
            domain: "mg.site.com",
            host: "api.eu.mailgun.net", // optional
            hostname: "api.eu.mailgun.net",
            apiKey: "API KEY",
            templates: {
                passwordResetEmail: {
                  subject: 'Reset your password',
                  pathPlainText: resolve(__dirname, '../email-templates/passwordReset.txt'),
                  pathHtml: resolve(__dirname, '../email-templates/passwordReset.html'),
                },
              }            
        }
    }
```

Clicking on the pw reset with the email address getting submitted results in this error

```
[1] { Error: 'to' parameter is missing
[1]     at IncomingMessage.res.on (/blah/blah/blah/server/node_modules/mailgun-js/lib/request.js:327:17)
[1]     at IncomingMessage.emit (events.js:203:15)
[1]     at IncomingMessage.EventEmitter.emit (domain.js:448:20)
[1]     at endReadableNT (_stream_readable.js:1129:12)
[1]     at process._tickCallback (internal/process/next_tick.js:63:19) statusCode: 400 }
```

Also just curious I had to create my own templates to use, I thought that the parse default ones would be used by default ?

**Comment by REPTILEHAUS** [comment]
aha, I see now the correct official package is `        module: '@parse/simple-mailgun-adapter',`
