### ISSUE TITLE
Wechat Mini Program

### ISSUE THREAD

**Issue by xianhaosui** [parse-community/Parse-SDK-JS#1127]
I use the uniapp multi platform of dcloud company to refer to the SDK of Wechat Mini Program and report the following error. What's the situation?
----------------------------------------------------------------
Version 2.11 is used, but the previous version 2.6 does not have this problem
----------------------------------------------------------------
code:
`import Parse from 'parse/weapp';
Parse.initialize('11a1c4d776cf0c86584afa2f16d79719', 'ff228d062059fbf3f38bc1c383bc7584');
----------------------------------------------------------------
error:
`
` #VM92 WAService.js:1 Uncaught TypeError: Function(...) is not a function
    at Object.129 (vendor.js:13)
    at o (vendor.js:13)
    at vendor.js:13
    at Object.130.regenerator-runtime (vendor.js:13)
    at o (vendor.js:13)
    at vendor.js:13
    at Object.24../CoreManager (vendor.js:13)
    at o (vendor.js:13)
    at vendor.js:13
    at Object.29../ParseACL (vendor.js:13)`

user Wechat development tools ,
error:
`VM365:1 thirdScriptError
Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at hasOwnProperty (<anonymous>)
    at t.exports (http://127.0.0.1:32511/appservice/utils/weapp.js:4851:18)
    at Object.t.exports [as f] (http://127.0.0.1:32511/appservice/utils/weapp.js:5490:33)
    at t.exports (http://127.0.0.1:32511/appservice/utils/weapp.js:4731:75)
    at Object.365.../internals/define-well-known-symbol (http://127.0.0.1:32511/appservice/utils/weapp.js:6108:49)
    at u (http://127.0.0.1:32511/appservice/utils/weapp.js:28:49)
    at http://127.0.0.1:32511/appservice/utils/weapp.js:29:18
    at Object.181.../../internals/wrapped-well-known-symbol (http://127.0.0.1:32511/appservice/utils/weapp.js:4224:7)
    at u (http://127.0.0.1:32511/appservice/utils/weapp.js:28:49)
    at http://127.0.0.1:32511/appservice/utils/weapp.js:29:18`

**Comment by dplewis** [comment]
Duplicate https://github.com/parse-community/Parse-SDK-JS/issues/916 . Check out that thread. Feel free to debug this and find a solution. Unfortunately we can test Wechat Mini Programs.

You might might have to stay 2.6.0.

**Comment by xianhaosui** [comment]
> Duplicate #916 . Check out that thread. Feel free to debug this and find a solution. Unfortunately we can test Wechat Mini Programs.
> 
> You might might have to stay 2.6.0.

Waiting for repair

**Comment by dplewis** [comment]
@xianhaosui We need developers like yourself using WeChat mini to fix this issue.

**Comment by lorki** [comment]
> > Duplicate #916 . Check out that thread. Feel free to debug this and find a solution. Unfortunately we can test Wechat Mini Programs.
> > You might might have to stay 2.6.0.
> 
> Waiting for repair

用在微信那种别扭的平台上还是最好用一个APIG来处理一下最好。

**Comment by dplewis** [comment]
Closing via https://github.com/parse-community/Parse-SDK-JS/issues/1331

Was told that the latest version of the SDK fixed this issue. Feel free to reopen if otherwise.
