### ISSUE TITLE
Parse.Object set Method not working in NativeScript

### ISSUE THREAD

**Issue by markusschmitz53** [parse-community/Parse-SDK-JS#1160]
### Issue Description
I'm trying to get Parse in NativeScript Vue working. I managed to initialize it using the workaround #939 (fixed the [first issue](https://github.com/parse-community/Parse-SDK-JS/issues/939) where _process.version_ was not set). I now tried to create a new Parse Object and set a string value on it which doesn't work. 

### Steps to reproduce

1. Install NativeScript Vue + Parse according to: https://nativescript-vue.org/blog/using-parse-in-nativescript-vue/

2. Add code from workaround #939 to node_modules/pbkdf2/lib/default-encoding.js:
`global.process = {
    browser : true,
    env     : {},
    version : "",
    versions: {node: false}
}`
(I also tried setting _browser_ to _false_ here but that didn't change anything)

3. Initialize Parse, create new object and set value (pretty much like the article says):
```require("nativescript-localstorage");
const Parse = require('parse');

Parse.initialize("apikey", "jskey");
Parse.serverURL = "https://parseapi.back4app.com/";
```
```const EventClass = Parse.Object.extend("Event");
const currentEvent = new EventClass();
currentEvent.set("myValue", "0");
```

### Expected Results

Value _myValue_ is set on new object instance _currentEvent_.

### Actual Outcome
Application crashes with error:
```An uncaught Exception occurred on "main" thread.
Calling js method onClick failed
TypeError: crypto.randomBytes is not a function
```

### Test Case

None

### Environment Setup

- **Server**
  - parse-server version: 3.9.0
  - Localhost or remote server? : **Remote on back4app.com**

- **JS SDK**
  - JS SDK version: 2.13.0
  - Application?: NativeScript Vue 2.5.0 Android application running on emulator

### Logs/Trace

```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onClick failed
System.err: TypeError: crypto.randomBytes is not a function
System.err:
System.err: StackTrace:
System.err: nodeRNG(file: node_modules\uuid\lib\rng.js:7:16)
System.err:     at v4(file: node_modules\uuid\v4.js:13:31)
System.err:     at value(file: node_modules\parse\lib\browser\ParseObject.js:311:30)
System.err:     at value(file: node_modules\parse\lib\browser\ParseObject.js:328:20)
System.err:     at get(file: node_modules\parse\lib\browser\ParseObject.js:2069:74)
System.err:     at value(file: node_modules\parse\lib\browser\ParseObject.js:986:35)
System.err:     at onTap(file: app\components\Mood.vue:127:0)
System.err:     at invokeWithErrorHandling(file: node_modules\nativescript-vue\dist\index.js:3368:25)
System.err:     at invoker(file: node_modules\nativescript-vue\dist\index.js:4032:13)
System.err:     at Observable.notify(file: node_modules\@nativescript\core\data\observable\observable.js:110:22)
System.err:     at Observable._emit(file: node_modules\@nativescript\core\data\observable\observable.js:127:17)
System.err:     at ClickListenerImpl.onClick(file: node_modules\@nativescript\core\ui\button\button.android.js:29:22)
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1160)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1138)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1134)
System.err:     at com.tns.gen.java.lang.Object_vendor_19449_26_ClickListenerImpl.onClick(Object_vendor_19449_26_ClickListenerImpl.java:18)
System.err:     at android.view.View.performClick(View.java:6597)
System.err:     at android.view.View.performClickInternal(View.java:6574)
System.err:     at android.view.View.access$3100(View.java:778)
System.err:     at android.view.View$PerformClick.run(View.java:25885)
System.err:     at android.os.Handler.handleCallback(Handler.java:873)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
System.err:     at android.os.Looper.loop(Looper.java:193)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6669)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by markusschmitz53** [comment]
still having this problem
