### ISSUE TITLE
localStorage is not defined when querying directly using JS SDK

### ISSUE THREAD

**Issue by andreisucman** [parse-community/Parse-SDK-JS#1847]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description

When querying Parse directly from frontend it says that localStorage is not defined. 

That could mean that I use node sdk, but I'm not. 

Here's how I import the module;

`import Parse from "parse";`

Same error happens if I import it like this

`import Parse from 'parse/dist/parse.min.js';`

or like this

`const Parse = (await import("parse")).default;`

Here is the query:

Parse.initialize(process.env.NEXT_PUBLIC_APP_ID);
Parse.serverURL = `${process.env.NEXT_PUBLIC_SERVER_URL}/parse`;

const qVar = new Parse.Query("Variables");
qVar.select("a", "b", "c");
const rVar = await qVar.first();
`

### Steps to reproduce

```
{
    "parse": "^4.0.1",
    "next": "^13.0.6",
    "react": "18.2.0",
    "react-dom": "18.2.0",
}
```

###  Environment
 Next.js 13.0.6

Server
- Parse Server version: `6.0.0`
- Operating system: `Win 10 x64 Intel 7`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): 'localhost:3001`

Database
- System (MongoDB or Postgres): `Mongo`
- Database version: `5.015`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Atlas`

Client
- Parse JS SDK version: `4.0.1`

### Logs

```
error - unhandledRejection: ReferenceError: localStorage is not defined
    at Object.getItem (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\parse\lib\browser\StorageController.browser.js:16:5)
    at Object.getItemAsync (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\parse\lib\browser\Storage.js:45:48)
    at Object.currentInstallationId (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\parse\lib\browser\InstallationController.js:26:29)
    at Object.request (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\parse\lib\browser\RESTController.js:374:54)
    at Object.find (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\parse\lib\browser\ParseQuery.js:3430:27)
    at ParseQuery.first (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\parse\lib\browser\ParseQuery.js:1521:45)
    at calculateExpectedKarma (webpack-internal:///./helpers/place-order/calculateExpectedKarma.js:15:29)
    at StepOne (webpack-internal:///./components/place-order/PlaceAnOrder/StepOne.js:69:105)
    at renderWithHooks (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5658:16)
    at renderIndeterminateComponent (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5731:15)
    at renderElement (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderHostElement (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5642:3)
    at renderElement (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderHostElement (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5642:3)
    at renderElement (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderElement (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5971:9)
    at renderNodeDestructiveImpl (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5785:7)
    at renderElement (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderHostElement (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5642:3)
    at renderElement (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (C:\Users\ANSU LLC\Desktop\project\frontend\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6141:7)

```

**Comment by nconfrey** [comment]
This can happen when you don't have cookies enabled in your browser--are you in Incognito or have cookies blocked? I'm also trying to debug the same issue, but I noticed it only repros without the ability to save cookies.

**Comment by andreisucman** [comment]
If anyone needs a workaround. You can define a cloud function on the server that would do the query and return the result. And then invoke the cloud function from the front end.

**Comment by dplewis** [comment]
If you are using NextJS ssr, then getServerSideProps won't have LocalStorage. 

* Use [@parse/react-ssr](https://github.com/parse-community/parse-react/blob/master/examples/next-ts-todo/pages/index.tsx)
* Use `parse/node` for ssr and `parse` for client
* Use your own `Parse.CoreManager.setStorageController()`

**Comment by dplewis** [comment]
Closing as this isn't an SDK issue
