### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by Mammut-Felix** [parse-community/Parse-SDK-JS#2204]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description

Parse-Server is not starting after update to parse 7.2.0

### Steps to reproduce

Update to parse 7.2.0

### Actual Outcome

Should work like before

### Expected Outcome

Should work like before

###  Environment

Server
- Parse Server version: `7.2.0`
- Operating system: `Docker image node:20.15.0-bookworm`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local / k8s`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `FILL_THIS_OUT`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `local / k8s`

Client
- Parse JS SDK version: `7.2.0`

### Logs

***/node_modules/@parse/push-adapter/lib/WEB.js:59
      var _ref = _asyncToGenerator( /*#__PURE__*/regeneratorRuntime.mark(function _callee(data, devices) {
                                                 ^

ReferenceError: regeneratorRuntime is not defined
    at /Users/felixnithammer/Documents/Projects/OSCABOServer/node_modules/@parse/push-adapter/lib/WEB.js:59:50
    at /Users/felixnithammer/Documents/Projects/OSCABOServer/node_modules/@parse/push-adapter/lib/WEB.js:134:6
    at Object.<anonymous> (/Users/felixnithammer/Documents/Projects/OSCABOServer/node_modules/@parse/push-adapter/lib/WEB.js:202:2)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/Users/felixnithammer/Documents/Projects/OSCABOServer/node_modules/@parse/push-adapter/lib/ParsePushAdapter.js:29:12)

Node.js v20.15.0

**Comment by dplewis** [comment]
@mtrezza Do you know why the push adapter is transcompiled using babel? I don't see developers using the adapter in a browser.

**Comment by dplewis** [comment]
@mtrezza I opened a PR for this https://github.com/parse-community/parse-server-push-adapter/pull/255

**Comment by mtrezza** [comment]
Great, I don't think it requires transcompilation, but we don't have any perf stats unfortunately. It's a small repo to probably not much of a difference?

I'll move this issue.
