### ISSUE TITLE
ParseQuery.containedIn - key $in must not start with '$'

### ISSUE THREAD

**Issue by abdielou** [parse-community/Parse-SDK-JS#400]
Using `parse-server` v2.2.25

Getting this error when querying `_Installation` on Cloud Code:

```
        var query = new Parse.Query(Parse.Installation);
        query.containedIn('channels',["stuff"]);
```

This is to be used as a Parse.Push query.

```
error: Error generating response. Error: key $in must not start with '$'
    at Error (native)
    at serializeInto (/some/where/node_modules/bson/lib/bson/parser/serializer.js:741:19)
    at serializeObject (/some/where/node_modules/bson/lib/bson/parser/serializer.js:300:18)
    at serializeInto (/some/where/node_modules/bson/lib/bson/parser/serializer.js:766:17)
    at serializeObject (/some/where/node_modules/bson/lib/bson/parser/serializer.js:300:18)
    at serializeInto (/some/where/node_modules/bson/lib/bson/parser/serializer.js:766:17)
    at serializeObject (/some/where/node_modules/bson/lib/bson/parser/serializer.js:300:18)
    at serializeInto (/some/where/node_modules/bson/lib/bson/parser/serializer.js:766:17)
    at serializeObject (/some/where/node_modules/bson/lib/bson/parser/serializer.js:300:18)
    at serializeInto (/some/where/node_modules/bson/lib/bson/parser/serializer.js:766:17) 
```

**Comment by abdielou** [comment]
Let me know if this looks more like a `parse-server` issue to then post it there.
