### ISSUE TITLE
Node - LiveQuery makes app crash when server restart or goes offline

### ISSUE THREAD

**Issue by rooswelt** [parse-community/Parse-SDK-JS#531]
In node environment, when connection with server is lost, live queries (if any) launches an exception that makes app crash

```
**********************************/node_modules/parse/lib/node/LiveQueryClient.js:607
              throw _iteratorError3;
              ^

Error: Unhandled "error" event. (undefined)
    at EventEmitter.emit (events.js:185:19)
    at Subscription.<anonymous> (**********************************/node_modules/parse/lib/node/ParseLiveQuery.js:233:28)
    at emitNone (events.js:110:20)
    at Subscription.emit (events.js:207:7)
    at LiveQueryClient.value (**********************************node_modules/parse/lib/node/LiveQueryClient.js:595:26)
    at WebSocket.socket.onerror (**********************************node_modules/parse/lib/node/LiveQueryClient.js:357:18)
    at WebSocket.onError (**********************************/node_modules/ws/lib/EventTarget.js:109:16)
    at emitOne (events.js:115:13)
    at WebSocket.emit (events.js:210:7)
    at ClientRequest._req.on (**********************************/node_modules/ws/lib/WebSocket.js:635:10)```

Any workaround or suggestion?

**Comment by rooswelt** [comment]
Digging more on source code I found a workaround:
Put a "on error" listener on each subscription
```
 subscription.on("error", error =>
      console.error("Subscription error");
    );
```
seem to solve the problem

**Comment by flovilmart** [comment]
So we can close?

**Comment by rooswelt** [comment]
For me it's still a bug, even if I found a workaround. Imho it makes no sense to require the error listener to let the app free-from-death.

Moreover "error" event for subscription is not even documented

**Comment by flovilmart** [comment]
Can you provide a pull request please?
