### ISSUE TITLE
Error: Failed to execute 'setRequestHeader' on 'XMLHttpRequest'

### ISSUE THREAD

**Issue by macklus** [parse-community/Parse-SDK-JS#561]
Some days ago i detect that using parse from Ionic always throws error:

```
{
   "code":100,
   "message":"XMLHttpRequest failed: {\"stack\":\"Error: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': 'function () {\\n        var args = [].slice.call(arguments),\\n          target = args.shift();\\n\\n        return args.reduce(function(base, obj) {\\n          Object.keys(obj).forEach(function(prop) {\\n            if (obj.hasOwnProperty(prop)) {\\n              base[prop] = obj[prop];\\n            }\\n          });\\n          return base;\\n        }, target);\\n      }' is not a valid HTTP header field value.\\n    at dispatch (file:///android_asset/www/build/vendor.js:134443:13)\\n    at Object.ajax (file:///android_asset/www/build/vendor.js:134446:7)\\n    at ParsePromise.<anonymous> (file:///android_asset/www/build/vendor.js:134524:29)\\n    at ParsePromise.wrappedResolvedCallback (file:///android_asset/www/build/vendor.js:20971:43)\\n    at ParsePromise.value (file:///android_asset/www/build/vendor.js:20909:36)\\n    at ParsePromise.<anonymous> (file:///android_asset/www/build/vendor.js:20981:29)\\n    at ParsePromise.wrappedResolvedCallback (file:///android_asset/www/build/vendor.js:20971:43)\\n    at ParsePromise.value (file:///android_asset/www/build/vendor.js:20909:36)\\n    at ParsePromise.<anonymous> (file:///android_asset/www/build/vendor.js:20981:29)\\n    at ParsePromise.wrappedResolvedCallback (file:///android_asset/www/build/vendor.js:20971:43)\"}"}", source: file:///android_asset/www/build/main.js (1393)
```
So far i see it could be an error on latest versions, because using apps with older versions dont show that mistake

**Comment by flovilmart** [comment]
It’s quite tough to figure out whar’s Going on in your built JS package. 

How is the Parse SDK Initialized?

**Comment by macklus** [comment]
Sorry, dont know what info do you need:

Current package.json parse:
```
"parse": "^1.11.1",
"@types/parse": "^2.4.7",
```

In app.component.ts (this is a Ionic app):
```
import Parse from 'parse';
import { AppConfig } from './app.config';

// Parse connect
Parse.serverURL = AppConfig.SERVER_URL;
Parse.initialize(AppConfig.APP_ID);
```

in app.config.ts:
```
export class AppConfig {
    /* Parse Server URL */
    public static get SERVER_URL(): string {
        return 'http://SERVER_IP_ADDRESS:1337/parse';
    }

    /* Parse App ID  */
    public static get APP_ID(): string {
        return 'MYAPPID';
    }
}
```

**Note:** only show Parse related code.

If you need more info, please, let me know.
thanks in advance

**Comment by flovilmart** [comment]
I suspect your code is improperly transpiled or interpreted.

What if you do:

```
Parse.initialize(‘appId’)
Parse.serverURL = ‘http://....’
```

**Comment by macklus** [comment]
After running some test....

If i run it on **ionic serve**, it works
when i deploy cordova app (**ionic cordova run android** or **ionic cordova run android --prod**), it fails

**Comment by flovilmart** [comment]
@macklus did you try what I suggested? You should probably open a question on stackoverflow as it seems unrelated to this SDK.

**Comment by macklus** [comment]
Just some info for help if someone go here from Google.

My problem was resolved by regenerate and update project. I update full ionic and cordova, create a empty project and add platforms, plugins and npm packages one by one. After that, everything works fine, so i suppoused if a versions problem.
