### ISSUE TITLE
Error: Cannot modify readonly attribute: sessionToken

### ISSUE THREAD

**Issue by GoGross** [parse-community/Parse-SDK-JS#677]
Parse-server 3.0.0
JS SDK 2.1.0

I get this error every-time I try to run the login function or the login after signup.
Everything else works just fine

origin=https://localhost:1984, user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36, dnt=1, content-type=text/plain, accept=*/*, referer=https://localhost:1984/auth, accept-encoding=gzip, deflate, br, accept-language=en-US,en;q=0.9, cookie=session=eyJjc3JmU2VjcmV0IjoiOWl2Wml2UHpMX3F3VUtkU3ozN3RwZWY2IiwiZmxhc2giOnt9LCJwYXNzcG9ydCI6eyJ1c2VyIjoiYWRtaW4ifX0=; session.sig=C_Gz2B3izpDM4kLw4VQdYbRDG_c, username=zealmurapa, password=********
error: Uncaught internal server error. Error: Cannot modify readonly attribute: sessionToken
    at ParseSession.value (/home/gross/apps/gross-framework/node_modules/parse-server/node_modules/parse/lib/node/ParseObject.js:727:17)
    at RestWrite.buildUpdatedObject (/home/gross/apps/gross-framework/node_modules/parse-server/lib/RestWrite.js:1135:17)
    at RestWrite.runAfterTrigger (/home/gross/apps/gross-framework/node_modules/parse-server/lib/RestWrite.js:1080:30)
    at Promise.resolve.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then (/home/gross/apps/gross-framework/node_modules/parse-server/lib/RestWrite.js:112:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7) Error: Cannot modify readonly attribute: sessionToken
    at ParseSession.value (/home/gross/apps/gross-framework/node_modules/parse-server/node_modules/parse/lib/node/ParseObject.js:727:17)
    at RestWrite.buildUpdatedObject (/home/gross/apps/gross-framework/node_modules/parse-server/lib/RestWrite.js:1135:17)
    at RestWrite.runAfterTrigger (/home/gross/apps/gross-framework/node_modules/parse-server/lib/RestWrite.js:1080:30)
    at Promise.resolve.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then (/home/gross/apps/gross-framework/node_modules/parse-server/lib/RestWrite.js:112:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
Error: Cannot modify readonly attribute: sessionToken
    at ParseSession.value (/home/gross/apps/gross-framework/node_modules/parse-server/node_modules/parse/lib/node/ParseObject.js:727:17)
    at RestWrite.buildUpdatedObject (/home/gross/apps/gross-framework/node_modules/parse-server/lib/RestWrite.js:1135:17)
    at RestWrite.runAfterTrigger (/home/gross/apps/gross-framework/node_modules/parse-server/lib/RestWrite.js:1080:30)
    at Promise.resolve.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then (/home/gross/apps/gross-framework/node_modules/parse-server/lib/RestWrite.js:112:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)

**Comment by GoGross** [comment]
Its from the client side in the browser, how can I share my private repo for your observation?

**Comment by flovilmart** [comment]
I don’t wish to spend hours debugging your issue. If you are unable to provide an example in the form of a pull request either on the JS SDK repo or this one then I definitely would suspect the issue is with you own custom code and not with the server. As for the explanation that this occurs ‘just by signing up’ but we don’t see it in our test logs, then i’d Be more than happy to hear the explanation and to merge the fix (or even provide it).

Where are the verbose logs that i also asked for in the original issue?

**Comment by GoGross** [comment]
Thanks @flovilmart we have had to rebuild server js, and so far so good, I think we have errors on our express configs, thanks much
