### ISSUE TITLE
Cloud Code Error: Parse.Config.save is not a function

### ISSUE THREAD

**Issue by camdagr8** [parse-community/Parse-SDK-JS#739]
**Parse Server Version:** 3.1.3
**Parse SDK Version:** 2.2.0
**Node:** 11.10.0
**NPM:** 6.7.0

I'm trying to update config values with a cloud code function and not having much success with the following code:

```js
const configGet = () => Parse.Config.get().then(config => config.attributes);

const configSet = async () => {
    // Get config
    const config = await configGet();

    // New values
    // TODO: get new values from req.params
    const params = { mic: 'check 1 2 3', test: 123 }; 

    // Save if we have new values
    const result =
        Object.keys(params).length > 0
            ? await Parse.Config.save(
                  { ...config, ...params, updated: Date.now() },
                  { useMasterKey: true },
              )
            : config;

    return result.attributes;
};

Parse.Cloud.define('config-get', configGet);
Parse.Cloud.define('config-set', configSet);
```

Any idea why I'm getting the following error: 

```
error: Parse.Config.save is not a function message=Parse.Config.save is not a function, stack=Error: Parse.Config.save is not a function
    at error (/Development/SolarSitesAdapter/node_modules/parse-server/lib/Routers/FunctionsRouter.js:121:16)
    at processTicksAndRejections (internal/process/next_tick.js:81:5), code=141
```

**Comment by camdagr8** [comment]
So after some inspection of ParseConfig.js, I tried the follow and was able to update config values:

```js

// Use Node version of Parse SDK
const ParseNode = require('parse/node');
ParseNode.initialize(ENV.APP_ID);
ParseNode.serverURL = ENV.PUBLIC_SERVER_URI + ENV.PARSE_MOUNT;
ParseNode.masterKey = ENV.MASTER_KEY;

const configGet = () => Parse.Config.get().then(config => config.attributes);

const configSet = async () => {
    // Get config
    const config = await configGet();

    // New values
    // TODO: get new values from req.params
    const params = { mic: 'check 1 2 3', test: 123 }; 

    // Save if we have new values
    const result =
        Object.keys(params).length > 0
            ? await ParseNode.Config.save(
                  { ...config, ...params, updated: Date.now() }
              )
            : config;

    return result.attributes;
};

Parse.Cloud.define('config-get', configGet);
Parse.Cloud.define('config-set', configSet);
```

**Comment by dplewis** [comment]
@camdagr8 This happens because Parse-Server currently uses version 2.1.0 of this SDK. You'll have to wait for the next server update. 

Your workaround forces 2.2.0 to be used.

**Comment by tutchmedia** [comment]
Hi @dplewis - any ideas on when a new server update will happen? I'm getting this exact same thing using Cloud Code in the Docker Container and the parse/node workaround doesn't seem to be working.

Thanks
