### ISSUE TITLE
Parse crashes with 'global.process undefined' error

### ISSUE THREAD

**Issue by bearoutthere** [parse-community/Parse-SDK-JS#939]
### Issue Description

Trying to install Parse into a Nativescript-Angular app following instructions for a Nativescript-Vue app [here](https://nativescript-vue.org/blog/using-parse-in-nativescript-vue/)
After including Parse and nativescript-localstorage as shown in the article, application crashes with the following error:

```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
System.err: TypeError: Cannot read property 'browser' of undefined
System.err: File: (file:///node_modules/pbkdf2/lib/default-encoding.js:3:11)
```

In the default-encoding.js  the offending code simply sets the defaultEncoding: 

```
if (process.browser) {
  defaultEncoding = 'utf-8'
} else {
  var pVersionMajor = parseInt(process.version.split('.')[0].slice(1), 10)

  defaultEncoding = pVersionMajor >= 6 ? 'utf-8' : 'binary'
}
```

The debugger shows that process object is undefined.  These errors only occur when Parse is included.  I've tried to create a placeholder process object and set its version to see what happens.  Another file in Parse plugin threw process.xxx undefined.  It appears that Process JS SDK is relying on process object which Nativescript does not provide.    Same happens with the Browser and Node versions.

We would really like to use Parse as our apps backend but unfortunately these issues block that.  Any ideas or suggestions would be greatly appreciated.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : [FILL THIS OUT]   2.8.4
  - Operating System:     [FILL THIS OUT]  MacOS
  - Hardware:             [FILL THIS OUT]  Macbook Pro
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): [FILL THIS OUT]   Back4App

- **JS SDK**
  - JS SDK version: [FILL THIS OUT] 2.7.1
  - Application? (Browser, Node, React-Native, etc): [FILL THIS OUT]   Browser and Node

webpack.config.js   sets process as 'global.process'

```
plugins: [
            // Define useful constants like TNS_WEBPACK
            new webpack.DefinePlugin({
                "global.TNS_WEBPACK": "true",
                "process": "global.process",
            }),
```

### Logs/Trace

```
bear$ tns run android --bundle
Searching for devices...
Starting Android emulator with image Nexus_5X_API_28
Waiting for emulator device initialization...
Preparing project...
File change detected. Starting incremental webpack compilation...

webpack is watching the files…

Hash: 5da13a38c315a1af2045
Version: webpack 4.30.0
Time: 7406ms
Built at: 10/02/2019 7:16:06 PM
              Asset       Size   Chunks             Chunk Names
          bundle.js   80.8 KiB   bundle  [emitted]  bundle
       package.json  112 bytes           [emitted]  
         runtime.js   71.4 KiB  runtime  [emitted]  runtime
tns-java-classes.js    0 bytes           [emitted]  
          vendor.js   16.5 MiB   vendor  [emitted]  vendor
Entrypoint bundle = runtime.js vendor.js bundle.js
[../$$_lazy_route_resource lazy recursive] ../$$_lazy_route_resource lazy namespace object 160 bytes {bundle} [built]
[./app.scss] 19.8 KiB {bundle} [built]
[./app/app-routing.module.tns.ts] 1.07 KiB {bundle} [built]
[./app/app.component.html] 64 bytes {bundle} [built]
[./app/app.component.scss] 19 bytes {bundle} [built]
[./app/app.component.ts] 983 bytes {bundle} [built]
[./app/app.module.tns.ts] 1.69 KiB {bundle} [built]
[./app/app.routes.ts] 243 bytes {bundle} [built]
[./app/home/home.component.html] 273 bytes {bundle} [built]
[./app/home/home.component.scss] 19 bytes {bundle} [built]
[./app/home/home.component.ts] 1.35 KiB {bundle} [built]
[./main.tns.ts] 2.37 KiB {bundle} [built]
[./package.json] 104 bytes {bundle} [optional] [built]
    + 959 hidden modules
Webpack compilation complete. Watching for file changes.
Webpack build done!
Project successfully prepared (android)
Successfully transferred bundle.js on device emulator-5554.
Successfully transferred runtime.js on device emulator-5554.
Successfully transferred vendor.js on device emulator-5554.
Restarting application on device emulator-5554...
Successfully synced application org.nativescript.izdmc on device emulator-5554.
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
System.err: TypeError: Cannot read property 'browser' of undefined
System.err: File: (file:///node_modules/pbkdf2/lib/default-encoding.js:3:11)
System.err: 
System.err: StackTrace: 
System.err:     ../node_modules/pbkdf2/lib/default-encoding.js(file:///node_modules/pbkdf2/lib/default-encoding.js:3:11)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at ../node_modules/pbkdf2/lib/sync.js(file:///node_modules/pbkdf2/lib/sync.js:14:22)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at ../node_modules/pbkdf2/index.js(file:///node_modules/pbkdf2/index.js:24:23)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at ../node_modules/crypto-browserify/index.js(file:///node_modules/crypto-browserify/index.js:14:8)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at ../node_modules/uuid/lib/rng.js(file:///node_modules/uuid/lib/rng.js:4:13)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at ../node_modules/uuid/v4.js(file:///node_modules/uuid/v4.js:1:10)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at ../node_modules/parse/lib/browser/AnonymousUtils.js(file:///node_modules/parse/lib/browser/AnonymousUtils.js:26:13)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at ../node_modules/parse/lib/browser/ParseUser.js(file:///node_modules/parse/lib/browser/ParseUser.js:33:45)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at ../node_modules/parse/lib/browser/ParseACL.js(file:///node_modules/parse/lib/browser/ParseACL.js:25:40)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at ../node_modules/parse/lib/browser/decode.js(file:///node_modules/parse/lib/browser/decode.js:19:39)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at ../node_modules/parse/lib/browser/Parse.js(file:///node_modules/parse/lib/browser/Parse.js:11:37)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at ../node_modules/parse/index.js(file:///node_modules/parse/index.js:1:17)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at ./app/home/home.component.ts(file:///src/app/home/home.component.ts:3:14)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at ./app/app.routes.ts(file:///src/app/app.routes.ts:3:0)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at ./app/app-routing.module.tns.ts(file:///data/data/org.nativescript.izdmc/files/app/bundle.js:51:77)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at ./app/app.module.tns.ts(file:///data/data/org.nativescript.izdmc/files/app/bundle.js:131:85)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at (file:///data/data/org.nativescript.izdmc/files/app/bundle.js:258:77)
System.err:     at ./main.tns.ts(file:///data/data/org.nativescript.izdmc/files/app/bundle.js:327:30)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at checkDeferredModules(file:///src/webpack/bootstrap:43:0)
System.err:     at webpackJsonpCallback(file:///src/webpack/bootstrap:30:0)
System.err:     at (file:///data/data/org.nativescript.izdmc/files/app/bundle.js:2:57)
System.err:     at require(:1:266)
System.err: 
System.err: 
System.err: TypeError: Cannot read property 'browser' of undefined
System.err: 
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
System.err: TypeError: Cannot read property 'browser' of undefined
System.err: File: (file:///node_modules/pbkdf2/lib/default-encoding.js:3:11)
System.err: 
System.err: StackTrace: 
System.err:     ../node_modules/pbkdf2/lib/default-encoding.js(file:///node_modules/pbkdf2/lib/default-encoding.js:3:11)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at ../node_modules/pbkdf2/lib/sync.js(file:///node_modules/pbkdf2/lib/sync.js:14:22)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at ../node_modules/pbkdf2/index.js(file:///node_modules/pbkdf2/index.js:24:23)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at ../node_modules/crypto-browserify/index.js(file:///node_modules/crypto-browserify/index.js:14:8)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at ../node_modules/uuid/lib/rng.js(file:///node_modules/uuid/lib/rng.js:4:13)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at ../node_modules/uuid/v4.js(file:///node_modules/uuid/v4.js:1:10)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at ../node_modules/parse/lib/browser/AnonymousUtils.js(file:///node_modules/parse/lib/browser/AnonymousUtils.js:26:13)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at ../node_modules/parse/lib/browser/ParseUser.js(file:///node_modules/parse/lib/browser/ParseUser.js:33:45)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at ../node_modules/parse/lib/browser/ParseACL.js(file:///node_modules/parse/lib/browser/ParseACL.js:25:40)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at ../node_modules/parse/lib/browser/decode.js(file:///node_modules/parse/lib/browser/decode.js:19:39)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at ../node_modules/parse/lib/browser/Parse.js(file:///node_modules/parse/lib/browser/Parse.js:11:37)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at ../node_modules/parse/index.js(file:///node_modules/parse/index.js:1:17)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at ./app/home/home.component.ts(file:///src/app/home/home.component.ts:3:14)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at ./app/app.routes.ts(file:///src/app/app.routes.ts:3:0)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at ./app/app-routing.module.tns.ts(file:///data/data/org.nativescript.izdmc/files/app/bundle.js:51:77)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at ./app/app.module.tns.ts(file:///data/data/org.nativescript.izdmc/files/app/bundle.js:131:85)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at (file:///data/data/org.nativescript.izdmc/files/app/bundle.js:258:77)
System.err:     at ./main.tns.ts(file:///data/data/org.nativescript.izdmc/files/app/bundle.js:327:30)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at checkDeferredModules(file:///src/webpack/bootstrap:43:0)
System.err:     at webpackJsonpCallback(file:///src/webpack/bootstrap:30:0)
System.err:     at (file:///data/data/org.nativescript.izdmc/files/app/bundle.js:2:57)
System.err:     at require(:1:266)
System.err: 
System.err: 
System.err: TypeError: Cannot read property 'browser' of undefined
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5876)
System.err:     at android.app.ActivityThread.access$1100(ActivityThread.java:199)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
System.err:     at android.os.Looper.loop(Looper.java:193)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6669)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
System.err: Caused by: com.tns.NativeScriptException: Error calling module function 
System.err: TypeError: Cannot read property 'browser' of undefined
System.err: File: (file:///node_modules/pbkdf2/lib/default-encoding.js:3:11)
System.err: 
System.err: StackTrace: 
System.err:     ../node_modules/pbkdf2/lib/default-encoding.js(file:///node_modules/pbkdf2/lib/default-encoding.js:3:11)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at ../node_modules/pbkdf2/lib/sync.js(file:///node_modules/pbkdf2/lib/sync.js:14:22)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at ../node_modules/pbkdf2/index.js(file:///node_modules/pbkdf2/index.js:24:23)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at ../node_modules/crypto-browserify/index.js(file:///node_modules/crypto-browserify/index.js:14:8)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at ../node_modules/uuid/lib/rng.js(file:///node_modules/uuid/lib/rng.js:4:13)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at ../node_modules/uuid/v4.js(file:///node_modules/uuid/v4.js:1:10)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at ../node_modules/parse/lib/browser/AnonymousUtils.js(file:///node_modules/parse/lib/browser/AnonymousUtils.js:26:13)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at ../node_modules/parse/lib/browser/ParseUser.js(file:///node_modules/parse/lib/browser/ParseUser.js:33:45)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at ../node_modules/parse/lib/browser/ParseACL.js(file:///node_modules/parse/lib/browser/ParseACL.js:25:40)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at ../node_modules/parse/lib/browser/decode.js(file:///node_modules/parse/lib/browser/decode.js:19:39)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at ../node_modules/parse/lib/browser/Parse.js(file:///node_modules/parse/lib/browser/Parse.js:11:37)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at ../node_modules/parse/index.js(file:///node_modules/parse/index.js:1:17)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at ./app/home/home.component.ts(file:///src/app/home/home.component.ts:3:14)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at ./app/app.routes.ts(file:///src/app/app.routes.ts:3:0)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at ./app/app-routing.module.tns.ts(file:///data/data/org.nativescript.izdmc/files/app/bundle.js:51:77)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at ./app/app.module.tns.ts(file:///data/data/org.nativescript.izdmc/files/app/bundle.js:131:85)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at fn(file:///src/webpack/bootstrap:120:0)
System.err:     at (file:///data/data/org.nativescript.izdmc/files/app/bundle.js:258:77)
System.err:     at ./main.tns.ts(file:///data/data/org.nativescript.izdmc/files/app/bundle.js:327:30)
System.err:     at __webpack_require__(file:///src/webpack/bootstrap:750:0)
System.err:     at checkDeferredModules(file:///src/webpack/bootstrap:43:0)
System.err:     at webpackJsonpCallback(file:///src/webpack/bootstrap:30:0)
System.err:     at (file:///data/data/org.nativescript.izdmc/files/app/bundle.js:2:57)
System.err:     at require(:1:266)
System.err: 
System.err: 
System.err: TypeError: Cannot read property 'browser' of undefined
System.err:     at com.tns.Runtime.runModule(Native Method)
System.err:     at com.tns.Runtime.runModule(Runtime.java:662)
System.err:     at com.tns.Runtime.run(Runtime.java:654)
System.err:     at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
System.err:     ... 8 more
File change detected. Starting incremental webpack compilation...
Hash: 2b7cfd237e4085806fcb
Version: webpack 4.30.0
Time: 964ms
Built at: 10/02/2019 7:16:48 PM
                                    Asset      Size   Chunks             Chunk Names
     5da13a38c315a1af2045.hot-update.json  62 bytes           [emitted]  
bundle.5da13a38c315a1af2045.hot-update.js  2.98 KiB   bundle  [emitted]  bundle
                                bundle.js  80.7 KiB   bundle  [emitted]  bundle
                               runtime.js  71.4 KiB  runtime  [emitted]  runtime
vendor.5da13a38c315a1af2045.hot-update.js  38.5 KiB   vendor  [emitted]  vendor
                                vendor.js  13.2 MiB   vendor  [emitted]  vendor
Entrypoint bundle = runtime.js vendor.js vendor.5da13a38c315a1af2045.hot-update.js bundle.js bundle.5da13a38c315a1af2045.hot-update.js
[../$$_lazy_route_resource lazy recursive] ../$$_lazy_route_resource lazy namespace object 160 bytes {bundle} [built]
[./app/app.module.tns.ts] 1.69 KiB {bundle} [built]
[./app/app.routes.ts] 243 bytes {bundle} [built]
[./app/home/home.component.ts] 1.36 KiB {bundle} [built]
    + 428 hidden modules
Webpack compilation complete. Watching for file changes.
Webpack build done!
Successfully transferred bundle.5da13a38c315a1af2045.hot-update.js on device emulator-5554.
Successfully transferred vendor.5da13a38c315a1af2045.hot-update.js on device emulator-5554.
Successfully transferred 5da13a38c315a1af2045.hot-update.json on device emulator-5554.
Successfully transferred bundle.js on device emulator-5554.
Successfully transferred runtime.js on device emulator-5554.
Successfully transferred vendor.js on device emulator-5554.
Restarting application on device emulator-5554...
```

**Comment by davimacedo** [comment]
Can you share the code that you are using to initialize the Parse SDK?

**Comment by dplewis** [comment]
I don't know much about native script. 

Can you try add the following to polyfill.ts or similar?

```
(window as any).global = window;
(window as any).process = window;
(window as any).process.browser = true;
(window as any).process.version = '';
(window as any).process.versions = {node: false};
```

Your webpack.DefinePlugin might also be overriding process.

**Comment by dplewis** [comment]
Closing as this is a WebPack issue and not a parse issue.

A fix would be to remove the `uuid` module and replace with a custom implementation but that doesn't fix your underlying issue.

**Comment by bearoutthere** [comment]
Thanks for the suggestions.  We managed to fix this issue by updating the offending file in one of the Parse dependencies. Replace contents of node_modules/pbkdf2/lib/default-encoding.js with the following:

```
var defaultEncoding
/* istanbul ignore next */
if (!global.process) {
 Object.assign(global, {
     process: {
         browser: false,
         env: {},
         version: "10.16.3"
     }
 });
}
if (process.browser) {
 defaultEncoding = 'utf-8'
} else {
 var pVersionMajor = parseInt(process.version.split('.')[0].slice(1), 10)
 defaultEncoding = pVersionMajor >= 6 ? 'utf-8' : 'binary'
}
module.exports = defaultEncoding

```

It's just a temporary workaround but it allowed us to use Parse with a Nativescript - Angular project.

**Comment by dplewis** [comment]
@bearoutthere I opened a PR to remove that module.

You have to be careful with your workaround. Calling npm install will undo your changes.
